<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>VisionAiChrono.Application</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>

    <ProjectReference Include="..\VisionAiChrono.Domain\VisionAiChrono.Domain.csproj" />
  </ItemGroup>
 
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
 
  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MailKit" Version="4.10.0" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.6.0" />
    <PackageReference Include="MimeKit" Version="4.10.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.6.0" />
  </ItemGroup>


</Project>
